services:
  kvstore-server:
    build:
      context: .
      dockerfile: Dockerfile.kvstore-server
    container_name: kvstore-server
    ports:
      - "${KVSTORE_PORT:-50051}:${KVSTORE_PORT:-50051}"
    networks:
      - kvstore-network
    environment:
      - KVSTORE_PORT=${KVSTORE_PORT:-50051}
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "${KVSTORE_PORT:-50051}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api-server:
    build:
      context: .
      dockerfile: Dockerfile.api-server
    container_name: api-server
    ports:
      - "${API_PORT:-8080}:${API_PORT:-8080}"
    depends_on:
      kvstore-server:
        condition: service_healthy
    networks:
      - kvstore-network
    environment:
      - API_PORT=${API_PORT:-8080}
      - GRPC_SERVER_ADDRESS=${GRPC_SERVER_ADDRESS:-kvstore-server:50051}
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:${API_PORT:-8080}/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  kvstore-network:
    driver: bridge
